Repository smeijer/next-runtime, pull requests merged in 2021-09, with the labels that each got.

#22 feat: rewrite of Form component and useFormSubmit hook
  docs/content/api/form.mdx
  docs/package-lock.json
  package-lock.json
  package.json
  pages/form-component.test.ts
  pages/form-component.tsx
  pages/login.tsx
  pages/multiple-forms.tsx
  pages/pending-nav.tsx
  src/app.tsx
  src/form.tsx
  src/lib/fetch-error.ts
  src/lib/use-refs.ts
  src/lib/use-safe-state.ts
Labels: 📦 feature, 💣️ breaking

#25 fix: make notFound() and redirect() return `never`
  package-lock.json
  package.json
  pages/pending-nav.tsx
  src/responses.ts
Labels: 🔧 internal

#26 feat: support Response throwing
  pages/response-throwing.test.ts
  pages/response-throwing.tsx
  src/handle.ts
Labels: 📦 feature

#27 fix: use current location as base url for form action
  .gitignore
  package-lock.json
  package.json
  pages/form-with-action.test.ts
  pages/form-with-action.tsx
  src/form.tsx
Labels: 🐛 bug, 📦 feature
